// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegisseurEnFilm.Domain.Data;

#nullable disable

namespace RegisseurEnFilm.Domain.Migrations
{
    [DbContext(typeof(FilmContext))]
    [Migration("20250409222220_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("RegisseurEnFilm.Domain.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Publicatiedatum")
                        .HasColumnType("TEXT");

                    b.Property<int>("RegisseurID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RegisseurID");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Publicatiedatum = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisseurID = 1,
                            Titel = "Horizon De Films"
                        },
                        new
                        {
                            Id = 2,
                            Publicatiedatum = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RegisseurID = 2,
                            Titel = "Horizon De Films"
                        });
                });

            modelBuilder.Entity("RegisseurEnFilm.Domain.Entities.Regisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Regisseurs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Jan Henken"
                        },
                        new
                        {
                            Id = 2,
                            Naam = "Simon Jansen"
                        });
                });

            modelBuilder.Entity("RegisseurEnFilm.Domain.Entities.Film", b =>
                {
                    b.HasOne("RegisseurEnFilm.Domain.Entities.Regisseur", "Regisseur")
                        .WithMany("Films")
                        .HasForeignKey("RegisseurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regisseur");
                });

            modelBuilder.Entity("RegisseurEnFilm.Domain.Entities.Regisseur", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
